### ISSUE TITLE
Carga y Limpieza de datos

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/FDS-2022-2-CC52#1]

**Comment by MarlonLLaguento** [comment]
Se analizó la data para identificar si había datos faltantes.

**Comment by SebastianOsorio20** [comment]
Se cargo correctamente el csv

**Comment by MarcDiazQ** [comment]
Se completaron los datos faltantes con la moda y media según corresponda.

**Comment by diegohumbser** [comment]
Se realizó la preparación de los datos para adaptarlos a técnicas de minería de datos que se van a utilizar posteriormente.
