### ISSUE TITLE
Crear Informe y ppt

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/FDS-2022-2-CC52#2]

**Comment by MarlonLLaguento** [comment]
El informe se basó en los resultados del procesamiento de los datos.

**Comment by SebastianOsorio20** [comment]
Se realizo un informe con todo lo requerido además de mostrar los cuadros estadísticos donde se detalla cada variable

**Comment by diegohumbser** [comment]
El informe abordó la selección de técnicas de modelado apropiadas para el proyecto y la evaluación del modelo teniendo en cuenta el cumplimiento de los criterios de éxito del problema.
