### ISSUE TITLE
Análisis y exploración de datos 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/FDS-2022-2-CC52#3]

**Comment by MarlonLLaguento** [comment]
Se utilizó las variables categóricas para la creación de tablas que ayudan en la formación del conocimiento.

**Comment by SebastianOsorio20** [comment]
Se determino que variables eran numéricas y que variables eran categóricas para su pronta limpieza

**Comment by MarcDiazQ** [comment]
Se realizó la visualización de los datos mediante gráficas que mostraban la relación entre las distintas variables.

**Comment by diegohumbser** [comment]
Se encontró una estructura general para los datos. Esto implica la aplicación de pruebas estadísticas básicas que revelen propiedades en los datos.
