### ISSUE TITLE
Metodología y conclusiones 

### ISSUE THREAD

**Issue by SebastianOsorio20** [SebastianOsorio20/FDS-2022-2-CC52#5]

**Comment by MarcDiazQ** [comment]
Se usó la metodología CRISP-DM para el desarrollo del proyecto.

**Comment by SebastianOsorio20** [comment]
Se trabajo en github para una optimización en el desarrollo del trabajo

**Comment by MarlonLLaguento** [comment]
Determinar los objetivos del proyecto fue clave para llevar a cabo la conversión de datos a conocimiento requerido por el cliente.

**Comment by diegohumbser** [comment]
La aplicación de la metodología CRISP-DM reduce la incertidumbre y la complejidad del proyecto y contribuye a que el cliente tenga una mayor comprensión y control de todo el proceso.
